# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class PhoneItem(scrapy.Item):
    # define the fields for your item here like:
    name = scrapy.Field()
    brand = scrapy.Field()
    model = scrapy.Field()
    category = scrapy.Field()
    price = scrapy.Field()
    network_type = scrapy.Field()
    network_2g = scrapy.Field()
    network_3g = scrapy.Field()
    network_4g = scrapy.Field()
    network_5g = scrapy.Field()
    speed = scrapy.Field()
    gprs = scrapy.Field()
    edge = scrapy.Field()
    launch_announcement = scrapy.Field()
    launch_date = scrapy.Field()
    body_dimensions = scrapy.Field()
    body_weight = scrapy.Field()
    build = scrapy.Field()
    network_sim = scrapy.Field()
    display_type = scrapy.Field()
    display_size = scrapy.Field()
    display_resolution = scrapy.Field()
    display_multitouch = scrapy.Field()
    display_density = scrapy.Field()
    display_screen_protection = scrapy.Field()
    operating_system = scrapy.Field()
    os_version = scrapy.Field()
    cpu = scrapy.Field()
    gpu = scrapy.Field()
    chipset = scrapy.Field()
    memory_internal = scrapy.Field()
    memory_external = scrapy.Field()
    ram = scrapy.Field()
    primary_camera = scrapy.Field()
    secondary_camera = scrapy.Field()
    camera_features = scrapy.Field()
    video = scrapy.Field()
    audio = scrapy.Field()
    loudspeaker = scrapy.Field()
    headphone_jack = scrapy.Field()
    wifi = scrapy.Field()
    bluetooth = scrapy.Field()
    usb = scrapy.Field()
    infrared = scrapy.Field()
    fm_radio = scrapy.Field()
    gps = scrapy.Field()
    sensors = scrapy.Field()
    messaging = scrapy.Field()
    browser = scrapy.Field()
    java = scrapy.Field()
    battery_type = scrapy.Field()
    battery_capacity = scrapy.Field()
    battery_stand_by = scrapy.Field()
    battery_talk_time = scrapy.Field()
    music = scrapy.Field()
    made_by = scrapy.Field()
    body_color = scrapy.Field()
    other_features = scrapy.Field()
    phone_url = scrapy.Field()
